# Generated by Django 5.2.3 on 2025-07-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dareexchange_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
