# Generated by Django 5.2.3 on 2025-07-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dareexchange_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='dare_image',
            field=models.ImageField(blank=True, null=True, upload_to='dare_images/'),
        ),
    ]
